<!-- GENERATED by scripts/sync.mjs — edit AGENTS.md, then re-run. -->
This repository is governed by an AI Engineering Baseline.
Read and follow **AGENTS.md** in the repository root. It is the canonical
entry point: navigation to architecture/, context/, standards/, skills/,
checklists/, verification/, and examples/, plus the rules and workflow
that apply to every task.
