import { cpSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { HarnessConfig } from "./types.js";

/**
 * Guides are feed-forward controls. Single-source them:
 *   AGENTS.md   — read natively by Claude Code, Copilot, and GitLab Duo;
 *                 nothing to generate, we only verify it exists.
 *   skills/     — copied to .claude/skills/ (Claude Code) and
 *                 .github/skills/ (Copilot). Duo project-level skills reach
 *                 flows via workspace context; AGENTS.md should reference them.
 *   .github/copilot-instructions.md — one-line pointer for older Copilot
 *                 surfaces that don't read AGENTS.md.
 * Copies, not symlinks: survives Windows checkouts and cloud coding agents.
 */
export function sync(config: HarnessConfig, cwd: string): string[] {
  const written: string[] = [];
  if (!existsSync(resolve(cwd, config.guides.canonical))) {
    throw new Error(`guides: canonical ${config.guides.canonical} not found — create it first`);
  }

  const pointer = join(cwd, ".github", "copilot-instructions.md");
  mkdirSync(join(cwd, ".github"), { recursive: true });
  writeFileSync(
    pointer,
    `<!-- GENERATED by 'harness sync' -->\nFollow the instructions in [AGENTS.md](../${config.guides.canonical}).\n`,
  );
  written.push(pointer);

  const skillsSrc = resolve(cwd, config.guides.skillsDir);
  if (existsSync(skillsSrc)) {
    for (const target of [join(cwd, ".claude", "skills"), join(cwd, ".github", "skills")]) {
      for (const skill of readdirSync(skillsSrc, { withFileTypes: true }).filter((d) => d.isDirectory())) {
        const dest = join(target, skill.name);
        cpSync(join(skillsSrc, skill.name), dest, { recursive: true });
        written.push(dest);
      }
    }
  }
  return written;
}
