#!/usr/bin/env node
/**
 * Layer 9 — multi-agent support. One canonical source (AGENTS.md); every
 * tool-specific file is GENERATED, never hand-edited. Zero dependencies.
 * Codex and GitLab Duo read AGENTS.md natively — no shim required.
 */
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";

const cwd = process.cwd();
if (!existsSync(join(cwd, "AGENTS.md"))) {
  console.error("AGENTS.md not found — the canonical source must exist first.");
  process.exit(1);
}

const BODY = `<!-- GENERATED by scripts/sync.mjs — edit AGENTS.md, then re-run. -->
This repository is governed by an AI Engineering Baseline.
Read and follow **AGENTS.md** in the repository root. It is the canonical
entry point: navigation to architecture/, context/, standards/, skills/,
checklists/, verification/, and examples/, plus the rules and workflow
that apply to every task.
`;

const SHIMS = [
  ".claude/CLAUDE.md",
  ".github/copilot-instructions.md",
  ".cursor/rules.md",
  ".gemini/GEMINI.md",
  ".windsurf/rules.md",
  ".clinerules",
  ".gitlab/duo/README.md", // Duo reads AGENTS.md natively; pointer for humans browsing .gitlab/
];

for (const shim of SHIMS) {
  const path = join(cwd, shim);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, BODY);
  console.log(`wrote ${shim}`);
}
